// Generated by scripts/train-local-model.mjs. Do not edit by hand.
export const localRecipeModelWeights = {
  "version": "1.6",
  "thresholds": {
    "ingredientMinScore": 2,
    "instructionMinScore": 4
  },
  "ingredient": {
    "measured": 5,
    "listed": 6,
    "multiWord": 2,
    "contextUse": 3,
    "descriptor": 1,
    "measurementNearby": 1,
    "termMention": 3,
    "negative": -3
  },
  "instruction": {
    "action": 6,
    "prep": 3,
    "ingredient": 3,
    "timing": 2,
    "sequence": 1,
    "negative": -6
  },
  "metadata": {
    "trainedExamples": 6,
    "ingredientLabels": 46,
    "stepLabels": 34
  }
} as const;
